controller_components:
  - credentials
controller_credentials:
  - name: student{{student_number}}_controller_cred
    credential_type: "Red Hat Ansible Automation Platform"
    organization: default
    inputs: 
      red_hat_ansible_automation_platform: student{{student_number}}.{{workshop_id}}.example.opentlc.com
      username: admin
      password: "{{workshop_password}}"
    ignore_errors: true